name: Sharun-Wrappe-Binary
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 7 1/21 * *" # We default to rebuilding every 21 days, change this to your liking
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          # comment out these 3 lines if aarch64 is not wanted
          - runs-on: ubuntu-24.04-arm
            name: Build AppImage
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@8872fabe63f9a00b35e25b2f46da62a05afc9a7d # v1
      - name: Install Dependencies
        run: /bin/sh ./get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./make-wrappe.sh
      - name: Upload artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Wrappe-${{ matrix.arch }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: Wrappe-*
          merge-multiple: true
      - name: Read version and get date
        shell: sh
        run: |
          echo "APPNAME=$(awk -F'=' '/^APPNAME=/ {print $2}' ./make-wrappe.sh)" >> "${GITHUB_ENV}"
          echo "VERSION=$(pacman -Q $APPNAME | awk '{print $2; exit}')" >> "${GITHUB_ENV}"
          echo "DATE=$(date +'%Y-%m-%d_%s')" >> "${GITHUB_ENV}"

      - name: Release Artifacts
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          name: "${{ env.APPNAME }}: ${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}@${{ env.DATE }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *wrappe*
